name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *"   # Updates twice a day
  workflow_dispatch:        # Manual trigger
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics-dashboard.svg
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
